# Generated by Django 4.1.5 on 2023-02-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrive", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thrive",
            old_name="description",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="thrive",
            old_name="reviewer",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="thrive",
            name="name",
        ),
        migrations.AddField(
            model_name="thrive",
            name="is_checked",
            field=models.BooleanField(default=0),
        ),
    ]
