# Generated by Django 4.1.5 on 2023-02-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thrive", "0002_rename_description_thrive_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thrive",
            name="rating",
        ),
    ]
